function [LSup,NSup] = genesups(fig_ori,supN)


%% superpixels generated by SLIC
[LSup,NSup] = superpixels(fig_ori,supN,'Compactness',20,'Method','slic','NumIterations',30);


%% show boundarymask
% BW_XXXX = boundarymask(LSup);imshow(imoverlay(fig_ori,BW_XXXX,'cyan'));
% keyboard

end
